Repository mgp25/Instagram-API, pull requests merged in 2019-10, with the labels that each got.

#2909 Client, Debug, & Request: Debugger improvements
  .github/ISSUE_TEMPLATE/bug-report.md
  src/Client.php
  src/Debug.php
  src/Request.php
Labels: enhancement

#2937 Media: Add getCommentInfos() function
  src/Request/Media.php
  src/Response/CommentInfosResponse.php
Labels: feature

#2938 Models: Update User Model
  src/Response/Model/User.php
Labels: enhancement, models

#2926 Settings: Add redis storage handler
  examples/customSettings.php
  src/Settings/Factory.php
  src/Settings/Storage/Redis.php
Labels: feature

#2944 Redis Storage Handler: Add ability to set hash prefix
  src/Settings/Factory.php
  src/Settings/Storage/Redis.php
Labels: enhancement
