Repository mgp25/Instagram-API, pull requests merged in 2019-06, with the labels that each got.

#2682 Instagram: Fix usernameHandler being unused
  src/Instagram.php
Labels: enhancement

#2698 Add module list for comment media
  src/Request/Media.php
Labels: documentation

#2709 Add support to read direct audio messages.
  src/Response/Model/AudioContext.php
  src/Response/Model/DirectThreadItem.php
  src/Response/Model/DirectThreadItemMedia.php
  src/Response/Model/Item.php
  src/Response/Model/VoiceMedia.php
Labels: models

#2715 InstagramPhoto: Add blurred border option
  src/Media/InstagramMedia.php
  src/Media/Photo/InstagramPhoto.php
Labels: feature, not ready for merge
